weiran.system.api_info :
  title : 系统接口
  type : array
  description : 系统信息接口调用, 系统信息返回的灵活数据
weiran.system.upload_type :
  title : 上传类型
  type : array
weiran.system.auth_access :
  title : 用户信息
  type : array
  description : 用户信息服务, 返回基础 pam 资料和自定义资料