<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePamPermissionTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('pam_permission', function (Blueprint $table) {
			$table->increments('id');
			$table->string('name', 255)->default('');
			$table->string('title', 255)->default('');
			$table->string('description', 255)->default('');
			$table->string('group', 50)->default('');
			$table->string('root', 50)->default('');
			$table->string('module', 50)->default('');
			$table->string('type', 50)->default('');

			$table->unique('name', 'permission_name_unique');


		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('pam_permission');
	}
}
